import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Build main.ts from src/ to main.js at root
const mainContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	outfile: "main.js",
	allowOverwrite: true
});

// Build styles.css from root to root (only if file exists)
const stylesPath = path.resolve('.', 'styles.css');
const hasStyles = fs.existsSync(stylesPath);

let stylesContext = null;
if (hasStyles) {
	stylesContext = await esbuild.context({
		entryPoints: ["styles.css"],
		bundle: true,
		logLevel: "info",
		minify: prod,
		outfile: "styles.css",
		allowOverwrite: true
	});
}

if (prod) {
	await mainContext.rebuild();
	if (stylesContext) {
		await stylesContext.rebuild();
		await stylesContext.dispose();
	}
	await mainContext.dispose();
	process.exit(0);
} else {
	await mainContext.watch();
	if (stylesContext) {
		await stylesContext.watch();
	}
	fs.writeFileSync(path.resolve('.', '.hotreload'), '')
}
